import { describe, expect, it } from 'vitest';
import { renderBoardMarkdown } from '../src/boards/board-generator';

describe('board generator', () => {
  it('renders generated board grouped by status', () => {
    const markdown = renderBoardMarkdown({
      boardTitle: 'Vibe Coding',
      generatedAt: '2026-04-23T00:00:00.000Z',
      issues: [
        { id: 'issue-1', title: 'First', status: 'READY', priority: 'high', project: 'kanban-task-engine', path: 'issues/vibe-coding/kanban-task-engine/issue-1.md' },
        { id: 'issue-2', title: 'Second', status: 'REVIEW', priority: 'medium', project: 'kanban-task-engine', path: 'issues/vibe-coding/kanban-task-engine/issue-2.md' },
      ],
    });

    expect(markdown).toContain('<!-- GENERATED BY kanban-task-engine. DO NOT EDIT DIRECTLY. -->');
    expect(markdown).toContain('## READY');
    expect(markdown).toContain('- [First](../issues/vibe-coding/kanban-task-engine/issue-1.md) `high`');
    expect(markdown).toContain('## REVIEW');
  });
});