import { IssueStatus, ISSUE_STATUSES } from '@kanban-task-engine/schema';

export interface BoardIssue {
  id: string;
  title: string;
  status: IssueStatus;
  priority: string;
  project: string;
  path: string;
}

export interface RenderBoardOptions {
  boardTitle: string;
  generatedAt: string;
  issues: BoardIssue[];
}

export function renderBoardMarkdown(options: RenderBoardOptions): string {
  const lines: string[] = [
    '<!-- GENERATED BY kanban-task-engine. DO NOT EDIT DIRECTLY. -->',
    '---',
    'type: kanban-board',
    `title: ${options.boardTitle}`,
    `generatedAt: ${options.generatedAt}`,
    '---',
    '',
    `# ${options.boardTitle}`,
    '',
  ];

  for (const status of ISSUE_STATUSES) {
    lines.push(`## ${status}`, '');
    const issues = options.issues.filter(issue => issue.status === status);
    if (issues.length === 0) {
      lines.push('- No issues', '');
      continue;
    }
    for (const issue of issues) {
      lines.push(`- [${issue.title}](../${issue.path}) \`${issue.priority}\` <!-- ${issue.id} -->`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}