import fs from 'fs/promises';
import path from 'path';
import YAML from 'yaml';

export type CliIssueStatus = 'TODO' | 'READY' | 'RUNNING' | 'REVIEW' | 'DONE' | 'FAILED';

export interface CliIssue {
  id: string;
  title: string;
  type: string;
  status: CliIssueStatus;
  priority: string;
  project: string;
  space: string;
  path: string;
  relativePath: string;
  executor?: string;
  workingDir?: string;
  mergeInto?: string;
}

export interface VaultIssueIndex {
  issues: CliIssue[];
  warnings: string[];
}

export interface UpdateIssueStatusOptions {
  status: CliIssueStatus;
  completed?: string;
  logMessage: string;
  now?: Date;
}

interface Registry {
  spaces?: Record<string, RegistrySpace>;
}

interface RegistrySpace {
  type?: string;
  issues?: string;
  projects?: Record<string, { path?: string }>;
}

const STATUSES: CliIssueStatus[] = ['TODO', 'READY', 'RUNNING', 'REVIEW', 'DONE', 'FAILED'];
const PRIORITY_RANK: Record<string, number> = { P0: 0, P1: 1, P2: 2, P3: 3 };

export async function loadVaultIssueIndex(vaultRoot: string): Promise<VaultIssueIndex> {
  const registry = await loadRegistry(vaultRoot);
  const warnings: string[] = [];
  const issues: CliIssue[] = [];

  for (const [spaceName, space] of Object.entries(registry.spaces ?? {})) {
    for (const issueRoot of issueRootsForSpace(space)) {
      const absoluteRoot = path.join(vaultRoot, issueRoot.path);
      const files = await listMarkdownFiles(absoluteRoot);

      for (const filePath of files) {
        try {
          const issue = await readCliIssue(filePath, vaultRoot, spaceName, issueRoot.project ?? '');
          if (issue.type !== 'epic') {
            issues.push(issue);
          }
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          warnings.push(`${path.relative(vaultRoot, filePath)}: ${message}`);
        }
      }
    }
  }

  issues.sort(compareIssues);
  return { issues, warnings };
}

export async function findIssueById(vaultRoot: string, issueId: string): Promise<CliIssue | null> {
  const { issues } = await loadVaultIssueIndex(vaultRoot);
  return issues.find(issue => issue.id === issueId) ?? null;
}

export async function updateIssueStatus(issue: CliIssue, options: UpdateIssueStatusOptions): Promise<void> {
  const document = await readIssueDocument(issue.path);
  const updatedAt = (options.now ?? new Date()).toISOString();
  const frontmatter: Record<string, unknown> = {
    ...document.frontmatter,
    status: options.status,
    updated: updatedAt,
  };

  if (options.completed) {
    frontmatter.completed = options.completed;
  }

  await writeIssueDocument(issue.path, frontmatter, appendLog(document.body, [
    `### ${updatedAt} ${issue.id} -> ${options.status}`,
    '',
    `- ${options.logMessage}`,
  ].join('\n')));
}

export function selectNextIssue(issues: CliIssue[]): CliIssue | null {
  return [...issues]
    .filter(issue => issue.status === 'READY')
    .sort(compareIssues)[0] ?? null;
}

export function renderIssueBoard(title: string, issues: CliIssue[], generatedAt: string): string {
  const lines = [
    '<!-- GENERATED BY kanban-task-engine. DO NOT EDIT DIRECTLY. -->',
    '---',
    'type: kanban-board',
    `title: ${title}`,
    `generatedAt: ${generatedAt}`,
    '---',
    '',
    `# ${title}`,
    '',
  ];

  for (const status of STATUSES) {
    lines.push(`## ${status}`, '');
    const matching = issues.filter(issue => issue.status === status);
    if (matching.length === 0) {
      lines.push('- No issues', '');
      continue;
    }

    for (const issue of matching) {
      lines.push(`- [${issue.title}](${issue.relativePath}) \`${issue.priority}\` <!-- ${issue.id} -->`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function issueRootsForSpace(space: RegistrySpace): Array<{ path: string; project?: string }> {
  if (space.type === 'container') {
    return Object.entries(space.projects ?? {})
      .filter((entry): entry is [string, { path: string }] => typeof entry[1].path === 'string')
      .map(([project, entry]) => ({ project, path: entry.path }));
  }

  return typeof space.issues === 'string' ? [{ path: space.issues }] : [];
}

async function loadRegistry(vaultRoot: string): Promise<Registry> {
  const registryPath = path.join(vaultRoot, 'registry.yaml');
  let parsed: unknown;
  try {
    parsed = YAML.parse(await fs.readFile(registryPath, 'utf8'));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Cannot read registry.yaml: ${message}`);
  }

  if (!isRecord(parsed) || !isRecord(parsed.spaces)) {
    throw new Error('registry.yaml must define spaces');
  }
  return parsed as Registry;
}

async function listMarkdownFiles(dir: string): Promise<string[]> {
  let entries: Array<import('fs').Dirent>;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') return [];
    throw error;
  }

  const files: string[] = [];
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === '_epics') continue;
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listMarkdownFiles(entryPath));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      files.push(entryPath);
    }
  }
  return files;
}

async function readCliIssue(filePath: string, vaultRoot: string, space: string, project: string): Promise<CliIssue> {
  const { frontmatter } = await readIssueDocument(filePath);
  const status = String(frontmatter.status ?? 'TODO');
  if (!STATUSES.includes(status as CliIssueStatus)) {
    throw new Error(`invalid status: ${status}`);
  }

  const id = requiredString(frontmatter, 'id');
  return {
    id,
    title: requiredString(frontmatter, 'title'),
    type: String(frontmatter.type ?? 'task'),
    status: status as CliIssueStatus,
    priority: String(frontmatter.priority ?? 'P2'),
    project: String(frontmatter.project ?? project),
    space,
    path: filePath,
    relativePath: path.relative(vaultRoot, filePath),
    executor: optionalString(frontmatter, 'executor'),
    workingDir: optionalString(frontmatter, 'working_dir'),
    mergeInto: optionalString(frontmatter, 'merge_into'),
  };
}

async function readIssueDocument(filePath: string): Promise<{ frontmatter: Record<string, unknown>; body: string }> {
  const content = await fs.readFile(filePath, 'utf8');
  const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const match = normalized.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  if (!match) {
    throw new Error('missing YAML frontmatter');
  }

  const frontmatter = parseFrontmatterBlock(match[1]);
  return {
    frontmatter,
    body: normalized.slice(match[0].length),
  };
}

async function writeIssueDocument(filePath: string, frontmatter: Record<string, unknown>, body: string): Promise<void> {
  const content = `---\n${YAML.stringify(frontmatter).trimEnd()}\n---\n\n${body.trimStart()}`;
  await fs.writeFile(filePath, content.endsWith('\n') ? content : `${content}\n`, 'utf8');
}

function parseFrontmatter(content: string): Record<string, unknown> {
  const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const match = normalized.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) {
    throw new Error('missing YAML frontmatter');
  }

  return parseFrontmatterBlock(match[1]);
}

function parseFrontmatterBlock(content: string): Record<string, unknown> {
  const parsed = YAML.parse(content);
  if (!isRecord(parsed)) {
    throw new Error('frontmatter must be an object');
  }
  return parsed;
}

function appendLog(body: string, entry: string): string {
  const normalized = body.trimEnd();
  if (/^## 로그\s*$/m.test(normalized)) {
    return `${normalized}\n\n${entry}\n`;
  }
  return `${normalized}\n\n## 로그\n\n${entry}\n`;
}

function compareIssues(a: CliIssue, b: CliIssue): number {
  return (PRIORITY_RANK[a.priority] ?? 99) - (PRIORITY_RANK[b.priority] ?? 99)
    || a.id.localeCompare(b.id);
}

function requiredString(input: Record<string, unknown>, field: string): string {
  const value = input[field];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`missing required field: ${field}`);
  }
  return value;
}

function optionalString(input: Record<string, unknown>, field: string): string | undefined {
  const value = input[field];
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === 'object' && input !== null && !Array.isArray(input);
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === 'object' && error !== null && 'code' in error;
}
